services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
    ports:
      - '${MYSQL_EX_PORT}:${MYSQL_IN_PORT}'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-app:
    build: .
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_IN_PORT}/${MYSQL_DATABASE}'
      - 'SPRING_DATASOURCE_USERNAME=${MYSQL_USER}'
      - 'SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}'
    ports:
      - '${SPRING_APP_PORT}:8080'
    volumes:
      - ./.env:/app/.env
    depends_on:
      - mysql