services:
  jenkins:
    image: 'jenkins/jenkins:lts-jdk21'
    container_name: jenkins
    ports:
      - "${JENKINS_PORT}:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - JENKINS_PORT=${JENKINS_PORT}
    networks:
      - 'jenkins_network'

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
    ports:
      - '${MYSQL_EX_PORT}:${MYSQL_IN_PORT}'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - 'jenkins_network'

  spring-app:
    build: .
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_IN_PORT}/${MYSQL_DATABASE}'
      - 'SPRING_DATASOURCE_USERNAME=${MYSQL_USER}'
      - 'SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}'
      - 'SPRING_PROFILE_ACTIVE=${SPRING_PROFILE_ACTIVE}'
    ports:
      - '${SPRING_APP_PORT}:8080'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - 'jenkins_network'

volumes:
  jenkins_home:

networks:
  jenkins_network: