spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  application:
    name: backend
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_IN_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver